- name: if
  hosts: localhost
  vars_prompt:
    - name: number
      prompt: Enter the Number
      private: false
  tasks:
    - name: given number less than 10
      ansible.builtin.debug:
        msg: "Give number {{number}} is less than 10"
      when: number < 10