- name: if
  hosts: localhost
  vars_prompt: #promots are alwasys considered as strings
  - name: number
    prompt: Enter the Number
    private: false
  tasks:
  - name: given number less than 10
    ansible.builtin.debug:
      msg: "Give number {{number}} is less than 10"
    when: number | int < 10
- name: lowercase
  hosts: localhost
  vars: 
    greeting: "HELLO"
  tasks:
  - name: print lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower }}, This is Kiran "
- name: uppercase
  hosts: localhost
  vars: 
    greeting: "hell"
  tasks:
  - name: print lower case
    ansible.builtin.debug:
      msg: "{{greeting | upper }}, This is Kiran "
- name: unique
  hosts: localhost
  vars:
    items: 
    - {'key': 'course', 'value':'Devops AWS'}
    - {'key': 'trainer', 'value': 'God'}
    - {'key': 'Duration', 'value': 233 hours}
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | items2dict}}"