- name: insatll packages
  hosts: web
  become: yes
  tasks:
  - name: loops
    ansible.builtin.dnf:
      name: "{{item}}"
      state: item.state
    loop:
    - { name: 'mysql', state: 'latest'  }
    - { name: 'nginx', state: 'absent'  }
    - { name: 'postfix', state: 'absent'  }