- name: insatll packages
  hosts: web
  become: yes
  tasks:
  - name: loops
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
      enabled: yes
    loop:
    - mysql
    - nginx
    - postfix