- name: connecting to host
  hosts: localhost
  become: yes
  tasks: installing nginx
  - name: Install
    ansible.builtin.dnf:
    name: nginx
    state: latest
  - name: run nginx
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes