- name: varibles
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: print information
    vars:
      course: Terraform
      Duration: 200 Hours
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} with {{Trainer}} for {{Duration}}"
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} with {{Trainer}} for {{Duration}}"