- name: varibles
  hosts: localhost
  vars_prompt:
  - name: course
    prompt: please enter course name
    private: false 
  vars:
    Trainer: Siva Kumar
    Duration: 150 hours
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} with {{Trainer}} for {{Duration}}"